# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 04:46
from __future__ import unicode_literals

import cuentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='T\xedtulo')),
                ('beginning', models.TextField(verbose_name='Inicio')),
                ('middle', models.TextField(verbose_name='Desarrollo')),
                ('end', models.TextField(verbose_name='Final')),
                ('storyimage', models.ImageField(upload_to=cuentos.models.file_path, verbose_name='Imagen del cuento')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuento',
                'verbose_name_plural': 'Cuentos',
            },
        ),
    ]
